"""
Cloud Custodian Dashboard - Simple Flask app to visualize policy results.
Reads the output directory generated by `custodian run` and displays results in a web UI.
"""

import json
import os
from pathlib import Path
from flask import Flask, jsonify, render_template

app = Flask(__name__)

OUTPUT_DIR = os.environ.get("C7N_OUTPUT_DIR", "../output")


def load_policy_results():
    """Load all policy results from the output directory."""
    results = []
    output_path = Path(OUTPUT_DIR)

    if not output_path.exists():
        return results

    for policy_dir in sorted(output_path.iterdir()):
        if not policy_dir.is_dir():
            continue

        resources_file = policy_dir / "resources.json"
        metadata_file = policy_dir / "metadata.json"

        policy_data = {
            "name": policy_dir.name,
            "resources": [],
            "resource_count": 0,
            "metadata": {},
        }

        if resources_file.exists():
            with open(resources_file) as f:
                resources = json.load(f)
                policy_data["resources"] = resources
                policy_data["resource_count"] = len(resources)

        if metadata_file.exists():
            with open(metadata_file) as f:
                policy_data["metadata"] = json.load(f)

        results.append(policy_data)

    return results


@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/results")
def api_results():
    results = load_policy_results()
    summary = {
        "total_policies": len(results),
        "total_violations": sum(r["resource_count"] for r in results),
        "compliant_policies": sum(1 for r in results if r["resource_count"] == 0),
        "non_compliant_policies": sum(1 for r in results if r["resource_count"] > 0),
    }
    return jsonify({"summary": summary, "policies": results})


if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
